name: Update IPs
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  
permissions:
  contents: write
  
jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update IPs
        run: python update.py
      # move all *.txt files to main branch
      - name: Commit Files
        run: |
          git config --global user.name 'mclarence'
          git config --global user.email 'mail@c-mes.net'
          mkdir -p /tmp/ips
          mv *.txt /tmp/ips
          git fetch --all
          git switch lists
          mv /tmp/ips/*.txt .
          rm requirements.txt
          git add .
          git commit -m "Update IPs"
          git push --set-upstream origin lists

