name: Update IPs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update IPs
        run: python update-ips.py
      # move all *.txt files to main branch
      - name: Commit Files
        run: |
          git config --global user.name 'mclarence'
          git config --global user.email 'mail@c-mes.net'
          mkdir -p /tmp/ips
          mv *.txt /tmp/ips
          git checkout -b lists
          mv /tmp/ips/*.txt .
          git add *.txt
          git commit -m "Update IPs"
          git push

